<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2010 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:clitype="clitype" xmlns:clm54217="urn:un:unece:uncefact:codelist:specification:54217:2001" xmlns:clm5639="urn:un:unece:uncefact:codelist:specification:5639:1988" xmlns:clm66411="urn:un:unece:uncefact:codelist:specification:66411:2001" xmlns:clmIANAMIMEMediaType="urn:un:unece:uncefact:codelist:specification:IANAMIMEMediaType:2003" xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:n1="urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2" xmlns:qdt="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2" xmlns:udt="urn:un:unece:uncefact:data:specification:UnqualifiedDataTypesSchemaModule:2" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:altova="http://www.altova.com" exclude-result-prefixes="cac cbc ccts clitype clm54217 clm5639 clm66411 clmIANAMIMEMediaType ext fn java link n1 qdt udt xbrldi xbrli xlink xs xsd xsi altova">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:decimal-format name="format1" grouping-separator=" " decimal-separator=","/>
	<xsl:template match="/">
		<html>
			<head>
				<title>
					<xsl:text> </xsl:text>
				</title>
				<style type="text/css">
					<xsl:comment>* { border-color:white;
font-size:medium;
font-weight:500;
 }
 * { font-size:small;
 }</xsl:comment>
				</style>
				<style type="text/css">@page { margin-left:0.6in; margin-right:0.6in; margin-top:0.79in; margin-bottom:0.79in } @media print { br.altova-page-break { page-break-before: always; } }</style>
			</head>
			<body>
				<table border="0" width="100%">
					<xsl:variable name="altova:CurrContextGrid_085946A8" select="."/>
					<tbody>
						<tr style="height:0.16in; ">
							<td style="border-color:white; font-size:small; font-weight:500; width:0.30in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.19in; ">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cac:AccountingSupplierParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PartyName">
													<xsl:for-each select="cbc:Name">
														<span style="font-size:medium; ">
															<xsl:apply-templates/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.68in; " valign="bottom"/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.03in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.92in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.09in; ">
								<span style="font-size:x-large; ">
									<xsl:text>Kreditnota</xsl:text>
								</span>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.05in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.05in; " align="right"/>
						</tr>
						<tr style="height:0.03in; ">
							<td style="border-color:white; font-size:small; font-weight:500; width:0.30in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.19in; ">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cac:AccountingSupplierParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PostalAddress">
													<xsl:for-each select="cbc:StreetName">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
								<span>
									<xsl:text>&#160;</xsl:text>
								</span>
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cac:AccountingSupplierParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PostalAddress">
													<xsl:for-each select="cbc:BuildingNumber">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.68in; ">
								<br/>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.03in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.92in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.09in; " valign="middle">
								<span>
									<xsl:text>Kreditnotanummer</xsl:text>
								</span>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.05in; ">
								<span>
									<xsl:text>:</xsl:text>
								</span>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.05in; " align="left">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cbc:ID">
											<xsl:apply-templates/>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
						</tr>
						<tr style="height:0.01in; ">
							<td style="border-color:white; font-size:small; font-weight:500; width:0.30in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.19in; ">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cac:AccountingSupplierParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PostalAddress">
													<xsl:for-each select="cbc:Postbox">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.68in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.03in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.92in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.09in; ">
								<span>
									<xsl:text>Kreditnotadato</xsl:text>
								</span>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.05in; ">
								<span>
									<xsl:text>:</xsl:text>
								</span>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.05in; " align="left">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cbc:IssueDate">
											<span>
												<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
												<xsl:text>. </xsl:text>
												<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
												<xsl:text>. </xsl:text>
												<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
											</span>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
						</tr>
						<tr style="height:0.01in; ">
							<td style="border-color:white; font-size:small; font-weight:500; width:0.30in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.19in; ">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cac:AccountingSupplierParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PostalAddress">
													<xsl:for-each select="cbc:PostalZone">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
								<span>
									<xsl:text>&#160;</xsl:text>
								</span>
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cac:AccountingSupplierParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PostalAddress">
													<xsl:for-each select="cbc:CityName">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.68in; ">
								<span>
									<xsl:text>&#160;</xsl:text>
								</span>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.03in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.92in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.09in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.05in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.05in; " align="left"/>
						</tr>
						<tr style="height:0.04in; ">
							<td style="border-color:white; font-size:small; font-weight:500; width:0.30in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.19in; " valign="bottom">
								<span>
									<xsl:text>Org.-/Bedriftsnummer:&#160; </xsl:text>
								</span>
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cac:AccountingSupplierParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PartyLegalEntity">
													<xsl:for-each select="cbc:CompanyID">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.68in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.03in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.92in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.09in; ">
								<span>
									<xsl:text>Kundenummer</xsl:text>
								</span>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.05in; ">
								<span>
									<xsl:text>:</xsl:text>
								</span>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.05in; " align="left">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cac:AccountingCustomerParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PartyIdentification">
													<xsl:for-each select="cbc:ID">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
						</tr>
						<tr style="height:0.09in; ">
							<td style="border-color:white; font-size:small; font-weight:500; width:0.30in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.19in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.68in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.03in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.92in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.09in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.05in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.05in; " align="right"/>
						</tr>
						<tr style="height:0.01in; ">
							<td style="border-color:white; font-size:small; font-weight:500; width:0.30in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.19in; ">
								<br/>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.68in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.03in; ">
								<span>
									<xsl:text>&#160;</xsl:text>
								</span>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.92in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.09in; ">
								<span>
									<xsl:text>Valuta</xsl:text>
								</span>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.05in; ">
								<span>
									<xsl:text>:</xsl:text>
								</span>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.05in; " align="left">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cbc:DocumentCurrencyCode">
											<xsl:apply-templates/>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
						</tr>
						<tr style="height:0.01in; ">
							<td style="border-color:white; font-size:small; font-weight:500; width:0.30in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.19in; ">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cac:AccountingCustomerParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PartyName">
													<xsl:for-each select="cbc:Name">
														<span style="font-size:medium; ">
															<xsl:apply-templates/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
								<span>
									<xsl:text>&#160;</xsl:text>
								</span>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.68in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.03in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.92in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.09in; ">
								<span>
									<xsl:text>Fakturaref.</xsl:text>
								</span>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.05in; ">
								<span>
									<xsl:text>:</xsl:text>
								</span>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.05in; " align="left">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cac:BillingReference">
											<xsl:for-each select="cac:InvoiceDocumentReference">
												<xsl:for-each select="cbc:ID">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
						</tr>
						<tr style="height:0.01in; ">
							<td style="border-color:white; font-size:small; font-weight:500; width:0.30in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.19in; ">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cac:AccountingCustomerParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PostalAddress">
													<xsl:for-each select="cbc:StreetName">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
								<span>
									<xsl:text>&#160;</xsl:text>
								</span>
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cac:AccountingCustomerParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PostalAddress">
													<xsl:for-each select="cbc:BuildingNumber">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.68in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.03in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.92in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.09in; ">
								<span>
									<xsl:text>Deres ref.</xsl:text>
								</span>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.05in; ">
								<span>
									<xsl:text>:</xsl:text>
								</span>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.05in; ">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cac:AccountingCustomerParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:Contact">
													<xsl:for-each select="cbc:ID">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
						</tr>
						<tr style="height:0.01in; ">
							<td style="border-color:white; font-size:small; font-weight:500; width:0.30in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.19in; ">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cac:AccountingCustomerParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PostalAddress">
													<xsl:for-each select="cbc:PostalZone">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
								<span>
									<xsl:text>&#160;</xsl:text>
								</span>
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cac:AccountingCustomerParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PostalAddress">
													<xsl:for-each select="cbc:CityName">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
								<br/>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.68in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.03in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.92in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.09in; " valign="top">
								<span>
									<xsl:text>Vår ref.</xsl:text>
								</span>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.05in; " valign="top">
								<span>
									<xsl:text>:</xsl:text>
								</span>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.05in; " align="left" valign="top">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cac:AccountingSupplierParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:Contact">
													<xsl:for-each select="cbc:ID">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
						</tr>
						<tr style="height:0.02in; ">
							<td style="border-color:white; font-size:small; font-weight:500; width:0.30in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.19in; ">
								<span>
									<xsl:text>Org.-/Bedriftsnummer:&#160; </xsl:text>
								</span>
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:CreditNote">
										<xsl:for-each select="cac:AccountingCustomerParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PartyLegalEntity">
													<xsl:for-each select="cbc:CompanyID">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.68in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.03in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.92in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.09in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.05in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.05in; " align="right"/>
						</tr>
						<tr style="height:0.08in; ">
							<td style="border-color:white; font-size:small; font-weight:500; width:0.30in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.19in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:3.68in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.03in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.92in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.09in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.05in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:1.05in; " align="right"/>
						</tr>
					</tbody>
				</table>
				<span>
					<xsl:text>&#160; </xsl:text>
				</span>
				<table border="0" width="100%">
					<xsl:variable name="altova:CurrContextGrid_08593628" select="."/>
					<tbody>
						<tr>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.10in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; ">
								<table border="1">
									<xsl:variable name="altova:CurrContextGrid_08593748" select="."/>
									<thead>
										<tr style="background-color:#e9ffe9; " bgcolor="gray">
											<th style="border-color:white; font-size:small; font-weight:500; width:3.09in; " align="left">
												<span style="font-weight:bold; ">
													<xsl:text> Artikkelnr.</xsl:text>
												</span>
											</th>
											<th style="border-color:white; font-size:small; font-weight:500; width:7.08in; " align="left">
												<span style="font-weight:bold; ">
													<xsl:text> Beskrivelse</xsl:text>
												</span>
											</th>
											<th style="border-color:white; font-size:small; font-weight:500; width:3.11in; " align="center">
												<span style="font-weight:bold; ">
													<xsl:text>Antall&#160; </xsl:text>
												</span>
											</th>
											<th style="border-color:white; font-size:small; font-weight:500; width:1.92in; " align="center">
												<span style="font-weight:bold; ">
													<xsl:text>Enhet</xsl:text>
												</span>
											</th>
											<th style="border-color:white; font-size:small; font-weight:500; width:1.69in; " align="right">
												<span style="font-weight:bold; ">
													<xsl:text>Pris&#160; </xsl:text>
												</span>
											</th>
											<th style="border-color:white; font-size:small; font-weight:500; width:2.17in; " align="right">
												<span style="font-weight:bold; ">
													<xsl:text>Linjebeløp</xsl:text>
												</span>
											</th>
										</tr>
									</thead>
									<tbody>
										<xsl:for-each select="$XML">
											<xsl:for-each select="n1:CreditNote">
												<xsl:for-each select="cac:CreditNoteLine">
													<tr>
														<td style="border-color:white; font-size:small; font-weight:500; width:3.09in; " align="left">
															<table border="0">
																<xsl:variable name="altova:CurrContextGrid_05D05678" select="."/>
																<tbody>
																	<xsl:for-each select="cac:Item">
																		<xsl:for-each select="cac:SellersItemIdentification">
																			<tr>
																				<td style="border-color:white; font-size:small; font-weight:500; " align="left">
																					<xsl:for-each select="cbc:ID">
																						<xsl:apply-templates/>
																					</xsl:for-each>
																				</td>
																			</tr>
																		</xsl:for-each>
																	</xsl:for-each>
																</tbody>
															</table>
														</td>
														<td style="border-color:white; font-size:small; font-weight:500; width:7.08in; " align="left">
															<table border="0">
																<xsl:variable name="altova:CurrContextGrid_05D05D38" select="."/>
																<tbody>
																	<xsl:for-each select="cac:Item">
																		<tr>
																			<td style="border-color:white; font-size:small; font-weight:500; " align="left">
																				<xsl:for-each select="cbc:Name">
																					<xsl:apply-templates/>
																				</xsl:for-each>
																			</td>
																		</tr>
																	</xsl:for-each>
																</tbody>
															</table>
														</td>
														<td style="border-color:white; font-size:small; font-weight:500; width:3.11in; " align="center">
															<xsl:for-each select="cbc:CreditedQuantity">
																<xsl:apply-templates/>
															</xsl:for-each>
														</td>
														<td style="border-color:white; font-size:small; font-weight:500; width:1.92in; " align="center">
															<table border="0">
																<xsl:variable name="altova:CurrContextGrid_05D05A98" select="."/>
																<tbody>
																	<xsl:for-each select="cbc:CreditedQuantity">
																		<tr>
																			<td style="border-color:white; font-size:small; font-weight:500; " align="center">
																				<xsl:for-each select="@unitCode">
																					<xsl:if test=".=&quot;NAR&quot;">
																						<span>
																							<xsl:text>Artikler</xsl:text>
																						</span>
																					</xsl:if>
																					<xsl:if test=".=&quot;KGM&quot;">
																						<span>
																							<xsl:text>Kilo</xsl:text>
																						</span>
																					</xsl:if>
																					<xsl:if test=".=&quot;NMP&quot;">
																						<span>
																							<xsl:text>Pakker</xsl:text>
																						</span>
																					</xsl:if>
																					<xsl:if test=".=&quot;LTR&quot;">
																						<span>
																							<xsl:text>Liter</xsl:text>
																						</span>
																					</xsl:if>
																					<xsl:if test=".=&quot;LH&quot;">
																						<span>
																							<xsl:text>Arbeidstime</xsl:text>
																						</span>
																					</xsl:if>
																					<xsl:if test=".=&quot;WM&quot;">
																						<span>
																							<xsl:text>Arbeidsmåned</xsl:text>
																						</span>
																					</xsl:if>
																					<xsl:if test=".=&quot;MTR&quot;">
																						<span>
																							<xsl:text>Meter</xsl:text>
																						</span>
																					</xsl:if>
																					<xsl:if test=".=&quot;IE&quot;">
																						<span>
																							<xsl:text>Person</xsl:text>
																						</span>
																					</xsl:if>
																					<xsl:if test=".=&quot;KWT&quot;">
																						<br/>
																						<span>
																							<xsl:text>Kilowatt</xsl:text>
																						</span>
																					</xsl:if>
																					<xsl:if test=".!=&quot;KGM&quot;">
																						<xsl:if test=".!=&quot;NAR&quot;">
																							<xsl:if test=".!=&quot;IE&quot;">
																								<xsl:if test=".!=&quot;MTR&quot;">
																									<xsl:if test=".!=&quot;KWT&quot;">
																										<xsl:if test=".!=&quot;WM&quot;">
																											<xsl:if test=".!=&quot;LTR&quot;">
																												<xsl:if test=".!=&quot;NMP&quot;">
																													<xsl:if test=".!=&quot;LH&quot;">
																														<span/>
																														<xsl:value-of select="string(.)"/>
																													</xsl:if>
																												</xsl:if>
																											</xsl:if>
																										</xsl:if>
																									</xsl:if>
																								</xsl:if>
																							</xsl:if>
																						</xsl:if>
																					</xsl:if>
																				</xsl:for-each>
																			</td>
																		</tr>
																	</xsl:for-each>
																</tbody>
															</table>
														</td>
														<td style="border-color:white; font-size:small; font-weight:500; width:1.69in; " align="right">
															<table border="0">
																<xsl:variable name="altova:CurrContextGrid_08B8F6E8" select="."/>
																<tbody>
																	<xsl:for-each select="cac:Price">
																		<tr>
																			<td style="border-color:white; font-size:small; font-weight:500; " align="right">
																				<xsl:for-each select="cbc:PriceAmount">
																					<span>
																						<xsl:value-of select="format-number(number(string(.)), '### ##0,00', 'format1')"/>
																					</span>
																				</xsl:for-each>
																			</td>
																		</tr>
																	</xsl:for-each>
																</tbody>
															</table>
														</td>
														<td style="border-color:white; font-size:small; font-weight:500; width:2.17in; " align="right">
															<xsl:for-each select="cbc:LineExtensionAmount">
																<span>
																	<xsl:value-of select="format-number(number(string(.)), '### ##0,00', 'format1')"/>
																</span>
															</xsl:for-each>
														</td>
													</tr>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</tbody>
								</table>
							</td>
						</tr>
					</tbody>
				</table>
				<br/>
				<table border="0" width="100%">
					<xsl:variable name="altova:CurrContextGrid_08B8F748" select="."/>
					<tbody>
						<tr>
							<td style="border-color:white; font-size:small; font-weight:500; "/>
							<td style="border-color:white; font-size:small; font-weight:500; "/>
							<td style="border-color:white; font-size:small; font-weight:500; ">
								<table border="0" width="100%">
									<xsl:variable name="altova:CurrContextGrid_08B8FC28" select="."/>
									<tbody>
										<tr style="height:0.07in; ">
											<td style="border-color:white; font-size:small; font-weight:500; width:8.20in; "/>
											<td style="border-color:white; font-size:small; font-weight:500; width:5.16in; " align="center">
												<span>
													<xsl:text>Totalt linjebeløp før MVA</xsl:text>
												</span>
											</td>
											<td style="border-color:white; font-size:small; font-weight:500; width:0.90in; " align="right">
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:CreditNote">
														<xsl:for-each select="cac:LegalMonetaryTotal">
															<xsl:for-each select="cbc:LineExtensionAmount">
																<span>
																	<xsl:value-of select="format-number(number(string(.)), '### ##0,00', 'format1')"/>
																</span>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
					</tbody>
				</table>
				<table border="0" width="100%">
					<xsl:variable name="altova:CurrContextGrid_08B8FAA8" select="."/>
					<tbody>
						<tr>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.23in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:12.04in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:5.26in; ">
								<br/>
								<table border="1">
									<xsl:variable name="altova:CurrContextGrid_08B900A8" select="."/>
									<thead>
										<tr style="background-color:#e9ffe9; height:0.17in; ">
											<th style="border-color:white; font-size:small; font-weight:500; width:1.48in; " align="right">
												<span style="font-weight:bold; ">
													<xsl:text>MVA grunnlag</xsl:text>
												</span>
											</th>
											<th style="border-color:white; font-size:small; font-weight:500; width:1.30in; " align="right">
												<span style="font-weight:bold; ">
													<xsl:text>MVA&#160;&#160;&#160;&#160;&#160; </xsl:text>
												</span>
											</th>
											<th style="border-color:white; font-size:small; font-weight:500; width:1.71in; " align="right">
												<span style="font-weight:bold; ">
													<xsl:text>MVA beløp</xsl:text>
												</span>
											</th>
										</tr>
									</thead>
									<tbody>
										<xsl:for-each select="$XML">
											<xsl:for-each select="n1:CreditNote">
												<xsl:for-each select="cac:TaxTotal">
													<xsl:for-each select="cac:TaxSubtotal">
														<tr>
															<td style="border-color:white; font-size:small; font-weight:500; width:1.48in; " align="right">
																<xsl:for-each select="cbc:TaxableAmount">
																	<span>
																		<xsl:value-of select="format-number(number(string(.)), '### ##0,00', 'format1')"/>
																	</span>
																</xsl:for-each>
															</td>
															<td style="border-color:white; font-size:small; font-weight:500; width:1.30in; " align="right">
																<table border="0">
																	<xsl:variable name="altova:CurrContextGrid_08B90888" select="."/>
																	<tbody>
																		<xsl:for-each select="cac:TaxCategory">
																			<tr>
																				<td style="border-color:white; font-size:small; font-weight:500; " align="right">
																					<xsl:for-each select="cbc:Percent">
																						<span>
																							<xsl:value-of select="format-number(number(string(.)), '##0', 'format1')"/>
																						</span>
																					</xsl:for-each>
																					<span>
																						<xsl:text> %</xsl:text>
																					</span>
																				</td>
																			</tr>
																		</xsl:for-each>
																	</tbody>
																</table>
															</td>
															<td style="border-color:white; font-size:small; font-weight:500; width:1.71in; " align="right">
																<xsl:for-each select="cbc:TaxAmount">
																	<span>
																		<xsl:value-of select="format-number(number(string(.)), '### ##0,00', 'format1')"/>
																	</span>
																</xsl:for-each>
															</td>
														</tr>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</tbody>
								</table>
							</td>
						</tr>
					</tbody>
				</table>
				<table border="0" width="100%">
					<xsl:variable name="altova:CurrContextGrid_08B90288" select="."/>
					<tbody>
						<tr>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.49in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; width:0.45in; "/>
							<td style="border-color:white; font-size:small; font-weight:500; ">
								<table border="0" width="100%">
									<xsl:variable name="altova:CurrContextGrid_08B90168" select="."/>
									<tbody>
										<tr>
											<td style="border-color:white; font-size:small; font-weight:500; "/>
											<td style="border-color:white; font-size:small; font-weight:500; "/>
											<td style="border-color:white; font-size:small; font-weight:500; " align="right">
												<span>
													<xsl:text>Total MVA:&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
												</span>
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:CreditNote">
														<xsl:for-each select="cac:TaxTotal">
															<xsl:for-each select="cbc:TaxAmount">
																<span>
																	<xsl:value-of select="format-number(number(string(.)), '### ##0,00', 'format1')"/>
																</span>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
										</tr>
										<tr>
											<td style="border-color:white; font-size:small; font-weight:500; "/>
											<td style="border-color:white; font-size:small; font-weight:500; "/>
											<td style="border-color:white; font-size:small; font-weight:500; " align="right">
												<span style="font-weight:bold; ">
													<xsl:text>Totalsum:</xsl:text>
												</span>
												<span>
													<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
												</span>
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:CreditNote">
														<xsl:for-each select="cac:LegalMonetaryTotal">
															<xsl:for-each select="cbc:PayableAmount">
																<span style="font-weight:bold; ">
																	<xsl:value-of select="format-number(number(string(.)), '### ##0,00', 'format1')"/>
																</span>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
					</tbody>
				</table>
				<br/>
				<br/>
				<br/>
				<br/>
				<br/>
				<span style="background-color:white; font-size:small; ">
					<xsl:text>&#160;</xsl:text>
				</span>
				<span style="font-size:small; ">
					<xsl:text>&#160;</xsl:text>
				</span>
				<xsl:for-each select="$XML"/>
				<br/>
				<span style="font-family:Arial; font-size:small; ">
					<xsl:text>&#160;</xsl:text>
				</span>
				<br/>
				<br/>
				<br/>
				<br/>
				<span style="font-size:small; text-align:right; ">
					<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
				</span>
				<br/>
				<span style="font-size:small; text-align:right; ">
					<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
				</span>
				<br/>
				<br/>
				<span style="font-size:small; ">
					<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
				</span>
				<br/>
				<br/>
				<span style="font-size:small; ">
					<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
				</span>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
